backend:
  name: git-gateway
  repo: rida10089-ai/portfolio
  branch: main

media_folder: "images"
public_folder: "/images"

site_url: https://lucent-llama-45824e.netlify.app
identity_url: https://lucent-llama-45824e.netlify.app/.netlify/identity

collections:
  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }